import type { Metadata } from "next";
import React from 'react';
import "./globals.css";

const interTightRegular = ({
  src: "./fonts/InterTight-Regular.ttf",
  variable: "--font-tight-regular"
});
const interTightMedium = ({
  src: "./fonts/InterTight-Medium.ttf",
  variable: "--font-tight-medium"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${interTightMedium.variable} ${interTightRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
